EmployeeManagementSystem/Controllers/DepartmentController.cs
using EmployeeManagementSystem.Models;
using EmployeeManagementSystem.Reposatory;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace EmployeeManagementSystem.Controllers
{
    
    public class DepartmentController : Controller
    {
        IDepartmentReposatory DeptRepo;
        private readonly IEmployeeReposatory empRepo;

        public DepartmentController(IDepartmentReposatory deptRepo , IEmployeeReposatory EmpRepo)
        {
            DeptRepo = deptRepo;
            empRepo = EmpRepo;
        }


        public IActionResult DeptEmps()
        {
            return View("DeptEmps" , DeptRepo.GetAll());
        }

        public IActionResult GetEmpsByDeptId(int deptid)
        {
           List<Employee>emplist = empRepo.GetEmpsByDeptId(deptid);

            return Json(emplist);
        }



        public IActionResult Index()
        {
          List<Department> departmentList = DeptRepo.GetAll();
           
            return View("Index" , departmentList);
        }

        


        public IActionResult Details(int id)
        {
            Department dept = DeptRepo.GetById(id);

            return View("Details", dept);
        }


     


        public IActionResult Edit( int id)
        {
            Department dept = DeptRepo.GetById(id);

            return View("Edit" ,dept);
        }


        [HttpPost]
        public IActionResult SaveEdit(Department deptFromREquest)
        {
            if (ModelState.IsValid)
            {
                DeptRepo.Update(deptFromREquest);
                DeptRepo.Save();
                return RedirectToAction("Index");
            }


            return View("Edit" , deptFromREquest);
        }




        public IActionResult Add()
        {

            return View("Add");

        }


        [HttpPost]
        public IActionResult SaveAdd(Department newdeptfromRequest)
        {
            if (ModelState.IsValid)
            {

                DeptRepo.Add(newdeptfromRequest);
                DeptRepo.Save();
                return RedirectToAction("Index");




            }


            return View("Add" , newdeptfromRequest);
        }


        
        public IActionResult Delete(int id)
        {

            return View("Delete",DeptRepo.GetById(id));
        }

        [HttpPost]
        public IActionResult ConfirmDelete(int id)
        {
            
            DeptRepo.Delete(id);
            DeptRepo.Save();
            return RedirectToAction("Index");


            
        }


    }
}

EmployeeManagementSystem/Controllers/EmployeeController.cs
using EmployeeManagementSystem.Filters;
using EmployeeManagementSystem.Models;
using EmployeeManagementSystem.Reposatory;
using EmployeeManagementSystem.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace EmployeeManagementSystem.Controllers
{
       
    public class EmployeeController : Controller
    {
        IEmployeeReposatory empRepo;
        IDepartmentReposatory deptRepo;
        public EmployeeController(IEmployeeReposatory _empRepo, IDepartmentReposatory _deptRepo)
        {
            empRepo = _empRepo;
            deptRepo = _deptRepo;


        }


        public ActionResult EmpCardPartial(int id)
        {

            return PartialView("_EmpCard" , empRepo.GetById(id));
        }




        [Authorize]
        public IActionResult Index()
        {


            return View("Index", empRepo.GetAll());
        }
       
        public IActionResult Add()
        {
            ViewData["deptList"] = deptRepo.GetAll();
            return View("Add");
        }


        public IActionResult SaveAdd(Employee empfromRequest)
        {
            if (ModelState.IsValid)
            {
                if (empfromRequest.DepartmentId != 0)
                {
                    empRepo.Add(empfromRequest);
                    empRepo.Save();
                    return RedirectToAction("Index");
                }
                else
                {

                    ModelState.AddModelError("DepartmentId", "select department ");
                }


            }

                ViewBag.deptList = deptRepo.GetAll();

                return View("Add", empfromRequest);
            
        }

      
            
            
            
            
            
            
            
            
            
            
            
            
            
            public IActionResult Edit(int id)
        {
            Employee empModel = empRepo.GetById(id);

            ViewBag.deptList = deptRepo.GetAll();

            return View("Edit", empModel);
        }

        [HttpPost]
        public IActionResult SaveEdit(EmployeeEditViewModel empFromRequest, int id)
        {
           
            if(ModelState.IsValid)
            {
                Employee EmpFromDB = empRepo.GetById(id);

                EmpFromDB.Name = empFromRequest.Name;
                EmpFromDB.Salary = empFromRequest.Salary;
                EmpFromDB.Address = empFromRequest.Address;
                EmpFromDB.ImageURL = empFromRequest.ImageURL;
                EmpFromDB.DepartmentId = empFromRequest.DepartmentId;
                EmpFromDB.JobTitle = empFromRequest.JobTitle;
                EmpFromDB.Id = empFromRequest.Id;

                empRepo.Update(EmpFromDB);
                empRepo.Save();
                return RedirectToAction("Index");


               

            }
            ViewData["deptList"] = deptRepo.GetAll();

            return View("Edit", empFromRequest);

        }

        public IActionResult Details(int id)
        {

            return View("Details",empRepo.GetById(id));
        }

        public IActionResult Delete(int id)
        {
            

            return View("Delete" , empRepo.GetById(id));
        }



        public IActionResult ConfirmDelete(int id)
        {
            
            empRepo.Delete(id);
            empRepo.Save();
            return RedirectToAction("Index");


           
        }

    }
}

EmployeeManagementSystem/Controllers/RoleController.cs
using EmployeeManagementSystem.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace EmployeeManagementSystem.Controllers
{

    [Authorize(Roles = "Admin")]
    public class RoleController : Controller
    {
        private readonly RoleManager<IdentityRole> roleManager;

        public RoleController(RoleManager<IdentityRole> roleManager)
        {
            this.roleManager = roleManager;
        }
        public IActionResult AddRole()
        {
            return View("AddRole");
        }

        [HttpPost]
        public async Task<IActionResult> SaveRole(RoleViewModel roleViewModel)
        {
            if (ModelState.IsValid)
            {
                IdentityRole role = new IdentityRole();
                role.Name = roleViewModel.RoleName;

                IdentityResult result =  await roleManager.CreateAsync(role);
                
                if (result.Succeeded)
                {
                    ViewBag.success = true;
                    return View("AddRole");


                }
                foreach (var item in result.Errors)
                {
                    ModelState.AddModelError("", item.Description);

                }

            }
            return View("AddRole", roleViewModel);
        }


    }
}

EmployeeManagementSystem/Views/Shared/_Advanced.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>@ViewData["Title"] - HR</title>

    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />

    <!-- Bootstrap icons-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet" />

    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="css/styles.css" rel="stylesheet" />
</head>

<body>
    <!-- Responsive navbar-->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container px-5">
            @* <a class="navbar-brand" href="#!">Start Bootstrap</a> *@

            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
           
            
            <partial name="_navpartial" />
          
        </div>
    </nav>

    <!-- Header -->
    <header class="bg-dark py-5">
        <div class="container px-5">

            @RenderBody()

            <div class="row gx-5 justify-content-center">
                <div class="col-lg-6">
                    <div class="text-center my-5">
                        <h1 class="display-5 fw-bolder text-white mb-2">
                            Present your business in a whole new way
                        </h1>
                      @*   <p class="lead text-white-50 mb-4">
                            Quickly design and customize responsive mobile-first sites with Bootstrap!
                        </p> *@
                        <div class="d-grid gap-3 d-sm-flex justify-content-sm-center">
                            <a class="btn btn-primary btn-lg px-4 me-sm-3" href="#features">Get Started</a>
                            <a class="btn btn-outline-light btn-lg px-4" href="#!">Learn More</a>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </header>

    <!-- Features section -->
    <section class="py-5 border-bottom" id="features">
        <div class="container px-5 my-5">
            <div class="row gx-5">

                <div class="col-lg-4 mb-5 mb-lg-0">
                    <div class="feature bg-primary bg-gradient text-white rounded-3 mb-3">
                        <i class="bi bi-collection"></i>
                    </div>
                    <h2 class="h4 fw-bolder">Featured title</h2>
                    <p>Paragraph of text beneath the heading to explain the heading.</p>
                    <a class="text-decoration-none" href="#!">
                        Call to action <i class="bi bi-arrow-right"></i>
                    </a>
                </div>

                <div class="col-lg-4 mb-5 mb-lg-0">
                    <div class="feature bg-primary bg-gradient text-white rounded-3 mb-3">
                        <i class="bi bi-building"></i>
                    </div>
                    <h2 class="h4 fw-bolder">Featured title</h2>
                    <p>Paragraph of text beneath the heading to explain the heading.</p>
                    <a class="text-decoration-none" href="#!">
                        Call to action <i class="bi bi-arrow-right"></i>
                    </a>
                </div>

                <div class="col-lg-4">
                    <div class="feature bg-primary bg-gradient text-white rounded-3 mb-3">
                        <i class="bi bi-toggles2"></i>
                    </div>
                    <h2 class="h4 fw-bolder">Featured title</h2>
                    <p>Paragraph of text beneath the heading to explain the heading.</p>
                    <a class="text-decoration-none" href="#!">
                        Call to action <i class="bi bi-arrow-right"></i>
                    </a>
                </div>

            </div>
        </div>
    </section>

    <!-- (جميع أجزاء الـ Pricing & Testimonials & Contact & Footer كما هي بدون حذف) -->
    <!-- Footer -->
    <footer class="py-5 bg-dark">
        <div class="container px-5">
            <p class="m-0 text-center text-white">Copyright &copy; Your Website 2023</p>
        </div>
    </footer>

    <!-- Bootstrap core JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>

    <!-- Core theme JS -->
    <script src="js/scripts.js"></script>

    <!-- SB Forms JS -->
    <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>

    @RenderSection("Scripts", required: false)

</body>
</html>

EmployeeManagementSystem/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EmployeeManagementSystem</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/EmployeeManagementSystem.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">EmployeeManagementSystem</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                      
                        
                        
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Department" asp-action="Index">Department</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                   
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employee" asp-action="Index">Employee</a>
                        </li>
                   
                    
                  
                    
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - EmployeeManagementSystem - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

EmployeeManagementSystem/Views/Shared/_NavPartial.cshtml
<div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        <li class="nav-item"><a class="nav-link active" aria-current="page" href="/Home">Home</a></li>
        <li class="nav-item"><a class="nav-link" href="#!">About</a></li>
        <li class="nav-item"><a class="nav-link" href="#!">Contact</a></li>
        <li class="nav-item"><a class="nav-link" href="#!">Services</a></li>


        @if (User.Identity.IsAuthenticated)
        {

            <li class="nav-item">
                <a class="nav-link" href="/Employee">Employee</a>
            </li>


            <li class="nav-item">
                <a class="nav-link" href="/Department">Department</a>
            </li>


            <li class="nav-item">
                <a class="nav-link" asp-controller="Account" asp-action="SignOut">LogOut</a>
            </li>


            @if (User.IsInRole("Admin"))
            {
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Role" asp-action="AddRole">Add Role</a>
                </li>
            }

            <li class="nav-item">
                <a class="nav-link" asp-controller="Account" asp-action="SignOut">Welcome @User.Identity.Name</a>
            </li>

        }
        else
        {


            <li class="nav-item">
                <a class="nav-link" asp-controller="Account" asp-action="Register">Register</a>
            </li>

            <li class="nav-item">
                <a class="nav-link" asp-controller="Account" asp-action="Login">Login</a>
            </li>
        }
    </ul>
</div>